export enum EventType
{
    SELECT_CHAT = "SELECT_CHAT",
    CLOSE_VIEW = "CLOSE_VIEW",
    OPEN_PROFILE = "OPEN_PROFILE",
    OPEN_CREATE_CHAT = "OPEN_CREATE_CHAT",
    OPEN_MOBILE_SIDEBAR = "OPEN_MOBILE_SIDEBAR",
};