export enum EventType
{
    SELECT_CHAT = "SELECT_CHAT",

    OPEN_PROFILE = "OPEN_PROFILE",
    OPEN_CREATE_CHAT = "OPEN_CREATE_CHAT",
    OPEN_MOBILE_SIDEBAR = "OPEN_MOBILE_SIDEBAR",

    CREATE_CHAT = "CREATE_CHAT",
    
    CLOSE_VIEW = "CLOSE_VIEW",
};